/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  images: {
    // Static export has no on-demand optimizer. Responsive screenshots are
    // pre-generated by scripts/prepare-assets.mjs and served via <Screenshot>.
    unoptimized: true,
  },
};

export default nextConfig;
