/** @type {import('next').NextConfig} */
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

const nextConfig = {
  output: 'export',
  basePath,
  assetPrefix: basePath,
  images: {
    // Static export has no on-demand optimizer. Responsive screenshots are
    // pre-generated by scripts/prepare-assets.mjs and served via <Screenshot>.
    unoptimized: true,
  },
};

export default nextConfig;
